"""Person model modified

Revision ID: 2dbde68801fb
Revises: e7dd3e9b5dc1
Create Date: 2019-04-04 13:01:13.067098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dbde68801fb'
down_revision = 'e7dd3e9b5dc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('person', sa.Column('land_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'person', ['email'])
    op.drop_constraint(None, 'person', type_='foreignkey')
    op.create_foreign_key(None, 'person', 'person', ['land_id'], ['id'])
    op.drop_column('person', 'ward_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('ward_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'person', type_='foreignkey')
    op.create_foreign_key(None, 'person', 'ward', ['ward_id'], ['id'])
    op.drop_constraint(None, 'person', type_='unique')
    op.drop_column('person', 'land_id')
    op.drop_column('person', 'email')
    # ### end Alembic commands ###
