"""empty message

Revision ID: 497d6979dc35
Revises: d8e7f2a8cda4
Create Date: 2019-04-09 06:57:39.842668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '497d6979dc35'
down_revision = 'd8e7f2a8cda4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('constituency', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'constituency', 'person', ['admin_id'], ['id'])
    op.add_column('county', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'county', 'person', ['admin_id'], ['id'])
    op.add_column('ward', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ward', 'person', ['admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ward', type_='foreignkey')
    op.drop_column('ward', 'admin_id')
    op.drop_constraint(None, 'county', type_='foreignkey')
    op.drop_column('county', 'admin_id')
    op.drop_constraint(None, 'constituency', type_='foreignkey')
    op.drop_column('constituency', 'admin_id')
    # ### end Alembic commands ###
