"""empty message

Revision ID: 5cc7e6e24957
Revises: 497d6979dc35
Create Date: 2019-04-11 05:31:37.381471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cc7e6e24957'
down_revision = '497d6979dc35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('constituency_admin_id_fkey', 'constituency', type_='foreignkey')
    op.drop_column('constituency', 'admin_id')
    op.drop_constraint('county_admin_id_fkey', 'county', type_='foreignkey')
    op.drop_column('county', 'admin_id')
    op.alter_column('person', 'area_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('ward_admin_id_fkey', 'ward', type_='foreignkey')
    op.drop_column('ward', 'admin_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ward', sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('ward_admin_id_fkey', 'ward', 'person', ['admin_id'], ['id'])
    op.alter_column('person', 'area_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('county', sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('county_admin_id_fkey', 'county', 'person', ['admin_id'], ['id'])
    op.add_column('constituency', sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('constituency_admin_id_fkey', 'constituency', 'person', ['admin_id'], ['id'])
    # ### end Alembic commands ###
