"""empty message

Revision ID: ecffacee0125
Revises: 5cc7e6e24957
Create Date: 2019-04-11 06:31:04.585122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecffacee0125'
down_revision = '5cc7e6e24957'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('area', sa.Column('lattitude', sa.Integer(), nullable=False))
    op.drop_column('area', 'Lattitude')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('area', sa.Column('Lattitude', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('area', 'lattitude')
    # ### end Alembic commands ###
